function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = -9999; // obj_light
	global.__objectDepths[1] = 0; // obj_evil
	global.__objectDepths[2] = -10; // obj_colision
	global.__objectDepths[3] = -100000; // obj_fade
	global.__objectDepths[4] = -100000; // obj_fadein
	global.__objectDepths[5] = -100000; // obj_fadeout
	global.__objectDepths[6] = -100000; // obj_fadeinlong
	global.__objectDepths[7] = 0; // obj_control
	global.__objectDepths[8] = -5; // obj_player
	global.__objectDepths[9] = 0; // obj_trail
	global.__objectDepths[10] = 0; // obj_trailslide
	global.__objectDepths[11] = -9999999; // obj_hud
	global.__objectDepths[12] = 0; // obj_jumpsmoke
	global.__objectDepths[13] = 0; // obj_wallsmoke
	global.__objectDepths[14] = -4; // obj_blink
	global.__objectDepths[15] = -20; // obj_boss
	global.__objectDepths[16] = -2; // obj_boss_atk
	global.__objectDepths[17] = 0; // obj_lighthouse
	global.__objectDepths[18] = -3; // obj_trash_ball
	global.__objectDepths[19] = -2; // obj_bosscar
	global.__objectDepths[20] = 0; // obj_eyel
	global.__objectDepths[21] = 0; // obj_eyer
	global.__objectDepths[22] = 5; // obj_bed
	global.__objectDepths[23] = 5; // obj_table
	global.__objectDepths[24] = 5; // obj_plantdecor
	global.__objectDepths[25] = 4; // obj_chest
	global.__objectDepths[26] = 5; // obj_closewindow
	global.__objectDepths[27] = -6; // obj_staircase
	global.__objectDepths[28] = 5; // obj_window
	global.__objectDepths[29] = 5; // obj_window2
	global.__objectDepths[30] = 5; // obj_puff
	global.__objectDepths[31] = 5; // obj_puff2
	global.__objectDepths[32] = 5; // obj_bookdecor
	global.__objectDepths[33] = 5; // obj_comber
	global.__objectDepths[34] = 5; // obj_closet2
	global.__objectDepths[35] = 5; // obj_tabledecor
	global.__objectDepths[36] = 5; // obj_rack
	global.__objectDepths[37] = 5; // obj_decor
	global.__objectDepths[38] = 5; // obj_rack2
	global.__objectDepths[39] = 5; // obj_socket
	global.__objectDepths[40] = 5; // obj_clock
	global.__objectDepths[41] = 5; // obj_bookself
	global.__objectDepths[42] = 0; // obj_self
	global.__objectDepths[43] = 5; // obj_computer
	global.__objectDepths[44] = 0; // obj_bench
	global.__objectDepths[45] = 0; // obj_wallamp
	global.__objectDepths[46] = 0; // obj_wallamp2
	global.__objectDepths[47] = 0; // obj_roof_lamp
	global.__objectDepths[48] = -7; // obj_paint
	global.__objectDepths[49] = -7; // obj_paint2
	global.__objectDepths[50] = -3; // obj_chair
	global.__objectDepths[51] = -1; // obj_statue
	global.__objectDepths[52] = -1; // obj_fridge
	global.__objectDepths[53] = -1; // obj_car
	global.__objectDepths[54] = -1; // obj_bigjbl
	global.__objectDepths[55] = -1; // obj_gas
	global.__objectDepths[56] = -1; // obj_oven
	global.__objectDepths[57] = -1; // obj_couch
	global.__objectDepths[58] = -1; // obj_lilcouch
	global.__objectDepths[59] = -1; // obj_table02
	global.__objectDepths[60] = -1; // obj_jbl
	global.__objectDepths[61] = -1; // obj_cactus
	global.__objectDepths[62] = 0; // obj_trailchair
	global.__objectDepths[63] = -1; // obj_rollingchair
	global.__objectDepths[64] = 0; // obj_box
	global.__objectDepths[65] = 0; // obj_closet
	global.__objectDepths[66] = 0; // obj_toolbox
	global.__objectDepths[67] = 0; // obj_dish_washer
	global.__objectDepths[68] = 0; // obj_candle
	global.__objectDepths[69] = -2; // obj_dish
	global.__objectDepths[70] = -2; // obj_tools
	global.__objectDepths[71] = -2; // obj_mug
	global.__objectDepths[72] = -2; // obj_fireball
	global.__objectDepths[73] = -2; // obj_plant
	global.__objectDepths[74] = -2; // obj_jar
	global.__objectDepths[75] = -2; // obj_rosevase
	global.__objectDepths[76] = -2; // obj_blender
	global.__objectDepths[77] = -2; // obj_microwave
	global.__objectDepths[78] = -2; // obj_tv
	global.__objectDepths[79] = -2; // obj_knife
	global.__objectDepths[80] = -2; // obj_fork
	global.__objectDepths[81] = -2; // obj_bottle
	global.__objectDepths[82] = -2; // obj_tabua
	global.__objectDepths[83] = -2; // obj_pan
	global.__objectDepths[84] = 0; // obj_trailball
	global.__objectDepths[85] = -2; // obj_ball
	global.__objectDepths[86] = -2; // obj_tire
	global.__objectDepths[87] = -2; // obj_dogplush
	global.__objectDepths[88] = -2; // obj_duck
	global.__objectDepths[89] = -2; // obj_plant02
	global.__objectDepths[90] = -2; // obj_mirror
	global.__objectDepths[91] = -2; // obj_guitar
	global.__objectDepths[92] = -2; // obj_book
	global.__objectDepths[93] = -2; // obj_lamp
	global.__objectDepths[94] = -2; // obj_trophy
	global.__objectDepths[95] = -2; // obj_bike
	global.__objectDepths[96] = -2; // obj_bowl
	global.__objectDepths[97] = -2; // obj_bule
	global.__objectDepths[98] = -2; // obj_bowl3
	global.__objectDepths[99] = -2; // obj_bowl2
	global.__objectDepths[100] = -2; // obj_plank
	global.__objectDepths[101] = -2; // obj_hat
	global.__objectDepths[102] = -2; // obj_vase
	global.__objectDepths[103] = -2; // obj_vase2
	global.__objectDepths[104] = -2; // obj_vase3
	global.__objectDepths[105] = -2; // obj_littlepaint
	global.__objectDepths[106] = 0; // obj_spike
	global.__objectDepths[107] = 0; // obj_spikeinv
	global.__objectDepths[108] = 0; // obj_sparkle
	global.__objectDepths[109] = -10; // obj_chocolate
	global.__objectDepths[110] = -10; // obj_sock
	global.__objectDepths[111] = -10; // obj_lollipop
	global.__objectDepths[112] = -10; // obj_pocket
	global.__objectDepths[113] = -5; // obj_water
	global.__objectDepths[114] = -5; // obj_vela
	global.__objectDepths[115] = -5; // obj_cruz
	global.__objectDepths[116] = -5; // obj_bible
	global.__objectDepths[117] = -5; // obj_oil
	global.__objectDepths[118] = 0; // obj_title
	global.__objectDepths[119] = 0; // obj_guris
	global.__objectDepths[120] = 0; // obj_credits
	global.__objectDepths[121] = 0; // obj_menu
	global.__objectDepths[122] = 0; // obj_language
	global.__objectDepths[123] = -9999999; // obj_pause
	global.__objectDepths[124] = 0; // obj_end
	global.__objectDepths[125] = 0; // obj_lighting
	global.__objectDepths[126] = 0; // obj_bestlight
	global.__objectDepths[127] = 0; // obj_next
	global.__objectDepths[128] = 0; // obj_platform
	global.__objectDepths[129] = 0; // obj_player_cutscene
	global.__objectDepths[130] = 0; // obj_slope
	global.__objectDepths[131] = 0; // obj_sound
	global.__objectDepths[132] = 2; // obj_placa1
	global.__objectDepths[133] = 2; // obj_placa2
	global.__objectDepths[134] = 2; // obj_placa3
	global.__objectDepths[135] = 2; // obj_placa4
	global.__objectDepths[136] = 2; // obj_placa5
	global.__objectDepths[137] = 2; // obj_placa6
	global.__objectDepths[138] = -99999; // obj_titlescreen
	global.__objectDepths[139] = 0; // obj_splash


	global.__objectNames[0] = "obj_light";
	global.__objectNames[1] = "obj_evil";
	global.__objectNames[2] = "obj_colision";
	global.__objectNames[3] = "obj_fade";
	global.__objectNames[4] = "obj_fadein";
	global.__objectNames[5] = "obj_fadeout";
	global.__objectNames[6] = "obj_fadeinlong";
	global.__objectNames[7] = "obj_control";
	global.__objectNames[8] = "obj_player";
	global.__objectNames[9] = "obj_trail";
	global.__objectNames[10] = "obj_trailslide";
	global.__objectNames[11] = "obj_hud";
	global.__objectNames[12] = "obj_jumpsmoke";
	global.__objectNames[13] = "obj_wallsmoke";
	global.__objectNames[14] = "obj_blink";
	global.__objectNames[15] = "obj_boss";
	global.__objectNames[16] = "obj_boss_atk";
	global.__objectNames[17] = "obj_lighthouse";
	global.__objectNames[18] = "obj_trash_ball";
	global.__objectNames[19] = "obj_bosscar";
	global.__objectNames[20] = "obj_eyel";
	global.__objectNames[21] = "obj_eyer";
	global.__objectNames[22] = "obj_bed";
	global.__objectNames[23] = "obj_table";
	global.__objectNames[24] = "obj_plantdecor";
	global.__objectNames[25] = "obj_chest";
	global.__objectNames[26] = "obj_closewindow";
	global.__objectNames[27] = "obj_staircase";
	global.__objectNames[28] = "obj_window";
	global.__objectNames[29] = "obj_window2";
	global.__objectNames[30] = "obj_puff";
	global.__objectNames[31] = "obj_puff2";
	global.__objectNames[32] = "obj_bookdecor";
	global.__objectNames[33] = "obj_comber";
	global.__objectNames[34] = "obj_closet2";
	global.__objectNames[35] = "obj_tabledecor";
	global.__objectNames[36] = "obj_rack";
	global.__objectNames[37] = "obj_decor";
	global.__objectNames[38] = "obj_rack2";
	global.__objectNames[39] = "obj_socket";
	global.__objectNames[40] = "obj_clock";
	global.__objectNames[41] = "obj_bookself";
	global.__objectNames[42] = "obj_self";
	global.__objectNames[43] = "obj_computer";
	global.__objectNames[44] = "obj_bench";
	global.__objectNames[45] = "obj_wallamp";
	global.__objectNames[46] = "obj_wallamp2";
	global.__objectNames[47] = "obj_roof_lamp";
	global.__objectNames[48] = "obj_paint";
	global.__objectNames[49] = "obj_paint2";
	global.__objectNames[50] = "obj_chair";
	global.__objectNames[51] = "obj_statue";
	global.__objectNames[52] = "obj_fridge";
	global.__objectNames[53] = "obj_car";
	global.__objectNames[54] = "obj_bigjbl";
	global.__objectNames[55] = "obj_gas";
	global.__objectNames[56] = "obj_oven";
	global.__objectNames[57] = "obj_couch";
	global.__objectNames[58] = "obj_lilcouch";
	global.__objectNames[59] = "obj_table02";
	global.__objectNames[60] = "obj_jbl";
	global.__objectNames[61] = "obj_cactus";
	global.__objectNames[62] = "obj_trailchair";
	global.__objectNames[63] = "obj_rollingchair";
	global.__objectNames[64] = "obj_box";
	global.__objectNames[65] = "obj_closet";
	global.__objectNames[66] = "obj_toolbox";
	global.__objectNames[67] = "obj_dish_washer";
	global.__objectNames[68] = "obj_candle";
	global.__objectNames[69] = "obj_dish";
	global.__objectNames[70] = "obj_tools";
	global.__objectNames[71] = "obj_mug";
	global.__objectNames[72] = "obj_fireball";
	global.__objectNames[73] = "obj_plant";
	global.__objectNames[74] = "obj_jar";
	global.__objectNames[75] = "obj_rosevase";
	global.__objectNames[76] = "obj_blender";
	global.__objectNames[77] = "obj_microwave";
	global.__objectNames[78] = "obj_tv";
	global.__objectNames[79] = "obj_knife";
	global.__objectNames[80] = "obj_fork";
	global.__objectNames[81] = "obj_bottle";
	global.__objectNames[82] = "obj_tabua";
	global.__objectNames[83] = "obj_pan";
	global.__objectNames[84] = "obj_trailball";
	global.__objectNames[85] = "obj_ball";
	global.__objectNames[86] = "obj_tire";
	global.__objectNames[87] = "obj_dogplush";
	global.__objectNames[88] = "obj_duck";
	global.__objectNames[89] = "obj_plant02";
	global.__objectNames[90] = "obj_mirror";
	global.__objectNames[91] = "obj_guitar";
	global.__objectNames[92] = "obj_book";
	global.__objectNames[93] = "obj_lamp";
	global.__objectNames[94] = "obj_trophy";
	global.__objectNames[95] = "obj_bike";
	global.__objectNames[96] = "obj_bowl";
	global.__objectNames[97] = "obj_bule";
	global.__objectNames[98] = "obj_bowl3";
	global.__objectNames[99] = "obj_bowl2";
	global.__objectNames[100] = "obj_plank";
	global.__objectNames[101] = "obj_hat";
	global.__objectNames[102] = "obj_vase";
	global.__objectNames[103] = "obj_vase2";
	global.__objectNames[104] = "obj_vase3";
	global.__objectNames[105] = "obj_littlepaint";
	global.__objectNames[106] = "obj_spike";
	global.__objectNames[107] = "obj_spikeinv";
	global.__objectNames[108] = "obj_sparkle";
	global.__objectNames[109] = "obj_chocolate";
	global.__objectNames[110] = "obj_sock";
	global.__objectNames[111] = "obj_lollipop";
	global.__objectNames[112] = "obj_pocket";
	global.__objectNames[113] = "obj_water";
	global.__objectNames[114] = "obj_vela";
	global.__objectNames[115] = "obj_cruz";
	global.__objectNames[116] = "obj_bible";
	global.__objectNames[117] = "obj_oil";
	global.__objectNames[118] = "obj_title";
	global.__objectNames[119] = "obj_guris";
	global.__objectNames[120] = "obj_credits";
	global.__objectNames[121] = "obj_menu";
	global.__objectNames[122] = "obj_language";
	global.__objectNames[123] = "obj_pause";
	global.__objectNames[124] = "obj_end";
	global.__objectNames[125] = "obj_lighting";
	global.__objectNames[126] = "obj_bestlight";
	global.__objectNames[127] = "obj_next";
	global.__objectNames[128] = "obj_platform";
	global.__objectNames[129] = "obj_player_cutscene";
	global.__objectNames[130] = "obj_slope";
	global.__objectNames[131] = "obj_sound";
	global.__objectNames[132] = "obj_placa1";
	global.__objectNames[133] = "obj_placa2";
	global.__objectNames[134] = "obj_placa3";
	global.__objectNames[135] = "obj_placa4";
	global.__objectNames[136] = "obj_placa5";
	global.__objectNames[137] = "obj_placa6";
	global.__objectNames[138] = "obj_titlescreen";
	global.__objectNames[139] = "obj_splash";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
